/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/dashboard/administration/automated-reports/': RouteRecordInfo<'/dashboard/administration/automated-reports/', '/dashboard/administration/automated-reports', Record<never, never>, Record<never, never>>,
    '/dashboard/administration/automated-reports/[id]': RouteRecordInfo<'/dashboard/administration/automated-reports/[id]', '/dashboard/administration/automated-reports/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/administration/users/': RouteRecordInfo<'/dashboard/administration/users/', '/dashboard/administration/users', Record<never, never>, Record<never, never>>,
    '/dashboard/administration/users/[id]/': RouteRecordInfo<'/dashboard/administration/users/[id]/', '/dashboard/administration/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/reports/some-report': RouteRecordInfo<'/dashboard/reports/some-report', '/dashboard/reports/some-report', Record<never, never>, Record<never, never>>,
  }
}
